name: Build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install requirements
      run: |
        sudo apt install -y build-essential gcc-13 libmbedtls-dev
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 60
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 60
    - name: 'Build NTAGTool'
      run: |
        make

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: >-
          git
          make
        pacboy: >-
          toolchain:p
          mbedtls:p
    - name: 'Build NTAGTool'
      run: |
        make
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ntagtool-win-x64
        path: ntagtool.exe
